### ISSUE TITLE
Docker can't run version 1.2.14 and 1.2.13

### ISSUE THREAD

**Issue by wizarden1** [wavesplatform/Waves#3304]
**Describe the bug**
Can't Start version 1.2.14 in docker.

**To Reproduce**
1. Run in Docker

**Expected behavior**
Run.

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version 16.04 LTS

**Additional context**
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/waves-node/starter.py", line 186, in <module>
    urllib.request.urlretrieve(url, file_path)
  File "/usr/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Node is starting...
Error: Unable to access jarfile /waves-node/waves-all-1.2.14.jar

**Comment by msmolyakov** [comment]
Hi, @wizarden1!

Could you please provide the exact command you're running?
And what image are you using? [node](https://hub.docker.com/r/wavesplatform/node) or [wavesnode](https://hub.docker.com/r/wavesplatform/wavesnode)?

**Comment by wizarden1** [comment]
I use this docker-compose file

version: "3.7"

services:
  waves:
    container_name: waves
    image: wavesplatform/node:latest
    environment:
      - WAVES_VERSION=1.2.14
      - WAVES_AUTODETECT_ADDRESS=yes
      - WAVES_NETWORK=TESTNET
# StdOut log Level: OFF, ERROR, WARN, INFO, DEBUG, TRACE
      - WAVES_LOG_LEVEL=INFO
      - WAVES_HEAP_SIZE=2g
      - WAVES__REST_API__ENABLE=yes
      - WAVES__REST_API__BIND_ADDRESS=0.0.0.0
    volumes:
      - ./data:/waves
    ports:
      - 6863:6863
      - 6869:6869
      - 6886:6886
    restart: always

networks:
  default:
    external:
      name: inet

**Comment by msmolyakov** [comment]
@wizarden1, sorry for the late reply.

The image [wavesplatform/node](http://hub.docker.com/r/wavesplatform/node) you're using is deprecated. Please try to use [wavesplatform/wavesnode](http://hub.docker.com/r/wavesplatform/wavesnode).

Example of compose file:
```yml
version: '3.8'
services:
  wavesnode:
    image: wavesplatform/wavesnode
    expose:
      - "6863"
      - "6869"
    ports:
      - "6863:6863"
      - "6869:6869"
    env_file:
     - .env
    volumes:
      - /docker/waves/waves-data:/var/lib/waves
      - /docker/waves/waves-config:/etc/waves
    restart: always
```
.env:
```properties
WAVES_WALLET_SEED=${BASE58_SEED}
WAVES_WALLET_PASSWORD=${WALLET_PASSWORD}
WAVES_NETWORK=TESTNET
JAVA_OPTS=-Dwaves.rest-api.enable=yes -Dwaves.rest-api.bind-address=0.0.0.0 -Dwaves.miner.enable=false
```
